---
# code: language=ansible

- name: Check if flux is installed
  ansible.builtin.stat:
    path: /usr/local/bin/flux
  register: flux_bin


- name: Install flux
  when: flux_bin.stat.exists is false
  block:
    - name: Download flux installation script
      ansible.builtin.get_url:
        url: https://fluxcd.io/install.sh
        dest: /tmp/install_flux.sh
        owner: root
        group: root
        mode: "0755"

    - name: Run flux installation script
      ansible.builtin.command:
        cmd: /tmp/install_flux.sh
        creates: /usr/local/bin/flux

    - name: Add flux completion for bash
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: source <(flux completion bash)


- name: Check if flux-system namespace exists in the cluster
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kube_path }}"
    kind: Namespace
    name: flux-system
  register: flux_ns


- name: Bootstrap flux
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -eo pipefail
      echo "{{ repo_token }}" \
        | flux bootstrap {{ provider }} \
            --token-auth \
            --owner={{ repo_owner }} \
            --repository={{ repo_name }} \
            --branch={{ repo_branch }} \
            --path={{ repo_path }} \
            {% if personal -%}--personal \{% endif -%}
            {% if  hostname | length > 0 -%}--hostname={{ hostname }}{% endif -%}
  when: flux_ns.resources | length == 0
  changed_when: false
