---
# code: language=ansible

- name: Configure nuc-server
  hosts: server
  roles:
    - name: Install ansible-pull service
      become: true
      role: systemd-timer
      tags: systemd-timer

  tasks:
    - name: Install SSH public key
      ansible.posix.authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRNjG2APH9L1DqkEkLaPRQtNJhlePFIKIO+z8Pz7D4o"
      tags: ssh-pubkey

    - name: Install mc
      become: true
      ansible.builtin.apt:
        package: mc
        state: present

    - name: Install Python client for Kubernetes
      become: true
      ansible.builtin.pip:
        name: kubernetes
        state: present
  tags: server-config


- name: Install Zerotier and join the network
  hosts: server
  become: true
  roles:
    - role: zerotier
  tags: zerotier


- name: Enable DNS in Zerotier network
  hosts: server
  become: true
  roles:
    - role: zeronsd
      zeronsd_zone: nucnet
  tags: zeronsd


- name: Deploy K3s cluster
  hosts: server
  become: true
  roles:
    - role: k3s
      install_k3s_exec: "server --disable=traefik --disable-helm-controller --disable-cloud-controller --disable-network-policy"
  tags: k3s

- name: Install and bootstrap flux
  hosts: server
  become: true
  roles:
    - role: flux
      repo_owner: laslopaul
      repo_path: "clusters/k3s"
  tags: flux
