---
# code: language=ansible

- name: Copy ansible-pull files to systemd folder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: Reload systemd daemons
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable ansible-pull timer
  ansible.builtin.systemd:
    unit: ansible-pull.timer
    state: started
    enabled: true
