---
# code: language=ansible

- name: Install Zerotier repo key
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg"
    dest: /etc/apt/trusted.gpg.d/zerotier.asc
    owner: root
    group: root
    mode: "0644"

- name: Install Zerotier package repo
  ansible.builtin.apt_repository:
    filename: zerotier
    repo: "deb http://download.zerotier.com/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"

- name: Install zerotier-one package
  ansible.builtin.apt:
    package: zerotier-one
    state: present
    update-cache: true

- name: Start and enable Zerotier service
  ansible.builtin.systemd_service:
    service: zerotier-one
    state: started
    enabled: true

- name: Find Zerotier network ids
  ansible.builtin.command: "zerotier-cli list-networks | tail -n +2 | cut -f3 -d' '"
  register: zerotier_networks
  changed_when: false

- name: Join Zerotier network
  ansible.builtin.command: "zerotier-cli join {{ zerotier_net_id }}"
  when: zerotier_net_id not in zerotier_networks.stdout_lines
  changed_when: false
