---
# code: language=ansible

- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    owner: root
    group: root
    mode: "0755"

- name: Run K3s installation script
  ansible.builtin.command:
    cmd: /tmp/install_k3s.sh
    creates: /etc/rancher/k3s/k3s.yaml
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: "{{ install_k3s_skip_download }}"
    INSTALL_K3S_SYMLINK: "{{ install_k3s_symlink }}"
    INSTALL_K3S_SKIP_ENABLE: "{{ install_k3s_skip_enable }}"
    INSTALL_K3S_SKIP_START: "{{ install_k3s_skip_start }}"
    INSTALL_K3S_VERSION: "{{ install_k3s_version }}"
    INSTALL_K3S_BIN_DIR: "{{ install_k3s_bin_dir }}"
    INSTALL_K3S_BIN_DIR_READ_ONLY: "{{ install_k3s_bin_dir_read_only }}"
    INSTALL_K3S_SYSTEMD_DIR: "{{ install_k3s_systemd_dir }}"
    INSTALL_K3S_EXEC: "{{ install_k3s_exec }}"
    INSTALL_K3S_NAME: "{{ install_k3s_name }}"
    INSTALL_K3S_TYPE: "{{ install_k3s_type }}"
    INSTALL_K3S_SELINUX_WARN: "{{ install_k3s_selinux_warn }}"
    INSTALL_K3S_SKIP_SELINUX_RPM: "{{ install_k3s_skip_selinux_rpm }}"
    INSTALL_K3S_CHANNEL_URL: "{{ install_k3s_channel_url }}"
    INSTALL_K3S_CHANNEL: "{{ install_k3s_channel }}"
